### ISSUE TITLE
Tile text breaks out of container at narrower widths

### ISSUE THREAD

**Issue by silent-e** [chiefpansancolt/simplecov-material#11]
**Describe the bug**
When the browser gets down to a certain width the text contained in the black tiles at the top breaks out of the tiles.  The width isn't even that narrow.  The attached screenshot is a 1000px width screenshot

**To Reproduce**
1. Run your tests to generate a simplecov report
2. Use your favorite method for responsive width testing.  I personally like the responsive mode via developer tools

**Expected behavior**
In a perfect world, the test would never break out of the box.  Using responsive techniques the tiles would rearrange themselves or redesign themselves to support varying widths.

**Screenshots**
<img width="1000" alt="Screen Shot 2019-12-04 at 1 13 29 PM" src="https://user-images.githubusercontent.com/25407/70186232-52ec0780-16a0-11ea-8808-c99bc795a4a0.png">

**Desktop (please complete the following information):**
 - OS: probably broadly affected
 - Browser: ditto

**Smartphone (please complete the following information):**
Currently not mobile-friendly.

**Additional context**
see discussion at pull request #9.  Issue submitted at the request of @chiefpansancolt

**Comment by chiefpansancolt** [comment]
@silent-e this is not handled in 0.5.0 with the left navigation being collapsible manually or auto when width gets to 1250 or less and the tiles stack when size gets to around 900px tablet size
