### ISSUE TITLE
Feature Request - Branch Coverage

### ISSUE THREAD

**Issue by rgranadino** [chiefpansancolt/simplecov-material#14]
**Is your feature request related to a problem? Please describe.**
With Ruby 2.5 Simplecov supports "branch coverage": 

> Add branch coverage measurement statistics to your results. Supported in CRuby versions 2.5+.

**Describe the solution you'd like**
It would be nice to have this coverage included in the HTML output like the `simplecov-html` gem does.

**Describe alternatives you've considered**
Current work around is to revert back to the `simplecov-html` gem. 

**Additional context**
Here is what the output looks like for both gems when branch coverage is enabled.

<img width="1000" alt="Screen Shot 2020-03-09 at 12 02 13 PM" src="https://user-images.githubusercontent.com/327608/76248318-568ead80-61fe-11ea-9de5-6fc811634545.png">
<img width="999" alt="Screen Shot 2020-03-09 at 12 03 52 PM" src="https://user-images.githubusercontent.com/327608/76248321-58587100-61fe-11ea-98c6-0f23ec62c81e.png">

**Comment by chiefpansancolt** [comment]
Thanks for the feedback, I will look to add the new branch coverage feature soon that was added to simplcov support!

**Comment by chiefpansancolt** [comment]
@rgranadino this is now included in v1.0.0 release coming in a day or two
