### ISSUE TITLE
Sorting by coverage % is sorting as a string, not numerically

### ISSUE THREAD

**Issue by silent-e** [chiefpansancolt/simplecov-material#8]
**Describe the bug**
Using localeCompare for sorting defaults to sorting each value as a string.  You need to sort numerically here.  See [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) on how to use `localeCompare`.

**String sort**
<img width="752" alt="string sort" src="https://user-images.githubusercontent.com/25407/70001967-8d746980-1513-11ea-9845-ce3eef13fb02.png">

**Numeric sort**
<img width="760" alt="numeric sort" src="https://user-images.githubusercontent.com/25407/70001965-8cdbd300-1513-11ea-84a5-05011def1272.png">

**To Reproduce**
1. Open a coverage report where you have mixed coverage.  0%, 100%, and some in between
2. Click on the % coverage header a few times to see how the sort changes
3. Note how it will probably read 0%, 100%, then the others in order

**Expected behavior**
You expect 0%, then increasing coverage percents up to the 100% at the end of the list, or beginning depending on if you're ascending or descending

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 78.0.3904.97

**Gem Version**
v0.4.0

**Additional context**
Simple fix.  just change the localeCompare line to …

````js
    return reverse * (a.cells[col].textContent.trim().localeCompare(b.cells[col].textContent.trim(), undefined, {numeric: true}));
````

This is how I got the Numeric Sort screenshot above.

**Comment by chiefpansancolt** [comment]
Will close this issue once new version is release later this week!

**Comment by chiefpansancolt** [comment]
@silent-e these updates are now live in version 0.5.0
